AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/BlockAlignment:
  EnforcedStyleAlignWith: either

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/WhileUntilModifier:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockNesting:
  Max: 5

Metrics/BlockLength:
  Max: 50

# YOU CAN PRY MY EMOJOIS FROM MY COLD DEAD HANDS
Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Max: 30